name: Build with IAR

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build with IAR
    strategy:
      matrix:
        project: [zephyr, PX5]
        arch: [Arm, RL78]
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "IAR ANSI C/C++ Compiler V9.70.1 for ${{ matrix.arch }}"
        sleep $((45 + RANDOM % 46))

  verify:
    needs: build
    name: Verify with IAR
    strategy:
      matrix:
        project: [zephyr, PX5]
        arch: [Arm, RL78]
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "IAR C-STAT Command Line Interface V2.7.5.559"
        sleep $((45 + RANDOM % 46))

  deploy:
    needs: verify
    name: Deploy with IAR
    strategy:
      matrix:
        project: [zephyr, PX5]
        arch: [Arm, RL78]
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "IAR C-SPY Command Line Utility V9.3.7.1266"
        sleep $((45 + RANDOM % 46))
