name: IAR Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build for Arm
    strategy:
      matrix:
        project: [Zephyr, PX5]
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/cxarm:9.60.4
    steps:
    - uses: actions/checkout@v4
    - run: |
        iarbuild project.ewp -build Debug -parallel 2

  build-rl78:
    name: Build for RL78
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/cxrl78:5.30.1
    steps:
    - uses: actions/checkout@v4
    - run: |
         iarbuild project.ewp -build Debug -parallel 2
  
  verify:
    needs: build
    name: Verify Arm
    strategy:
      matrix:
        project: [Zephyr, PX5]
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/cxarm:9.60.4
    steps:
    - uses: actions/checkout@v4
    - run: |
         iarbuild project.ewp -cstat_analyze Debug -parallel 2

  verify-rl78:
    needs: build-rl78
    name: Verify RL78
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/cxrl78:5.30.1
    steps:
    - uses: actions/checkout@v4
    - run: |
        iarbuild project.ewp -cstat_analyze Debug -parallel 2     

  deploy:
    needs: verify
    name: Deploy Arm
    strategy:
      matrix:
        project: [Zephyr, PX5]
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/cxarm:9.60.4
    steps:
    - uses: actions/checkout@v4
    - run: |
        iarbuild project.ewp -deploy Release

  deploy-rl78:
    needs: verify-rl78
    name: Deploy RL78
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/cxrl78:5.30.1
    steps:
    - uses: actions/checkout@v4
    - run: |
        iarbuild project.ewp -deploy Release
